"use strict";
const district = "Naogaon";
const stock = 149;
const isAvailable = false;
let input = 'Hello';
input = 543;
console.log(district);
console.log(stock);
console.log(isAvailable);
console.log(input);
